= Archived
:toc: auto

実験等で過去に利用したものたち（或いは没になったもの）。
今後参照するかもしれないと考えて、念のため置かれている。
コミットログから参照できるものたちであるから、レポジトリから消してしまってもよいかも知れない。

multi-runner::
任意のアプリケーションを任意個数並列に動かすためのプログラム．
特にコマンドライン引数やconfigファイルに対応させていないため，毎度書き換えてコンパイルさせる必要がある．
そして，任意秒数後に全てのサブプロセスにSIGINTを送る．

script::
matplotlibを利用してグラフを生成するスクリプト群．

simple-wagi::
under constructed :)

single-sched/crate/manager-v2::
最もシンプルなサブプロセスのハンドリング＆計測プログラム．
コンフィグファイルをもとにサブプロセス1つ起動する．
そして，10秒毎にメモリ使用量をprocfsから取得する．

wasm-test-app::
ハンドリングされる対象．
WebAssemblyアプリケーションのプログラム．

workdir::
実際に動作させるときの作業ディレクトリ． +
他のディレクトリで書いたプログラムのコンパイル結果のバイナリをコピーするなどして実行している．
実行時に生成されたデータも，このディレクトリ配下に保存されている．

/wasm-mem-sched::
configファイルをもとに任意個数のWebAssemblyアプリケーション（実態はサブプロセス）を同時にハンドリングするつもりだったもの．
kubeletやkrustletを参考にした．
channelを利用した並行プログラミングや，redisを利用したハンドリング対象のサブプロセスの状態管理などモリモリにして書いていた（が，研究でそこまで高機能にする必要がなかったため途中で没になった）．

/single-sched::
crates/executorとcrates/managerでセット． +
executorは，managerの指示をgrpc経由で受け取ってWebAssemblyアプリケーションの起動と停止をする．
managerは，executorのメモリ使用量を監視 (procfsを読んでUSSを計算) して，定められた閾値以上になったら，executorで実行中のWebAssemblyアプリケーションの再起動するように命令する．
executorでMutexのlockがずっと取れないという不具合のため一旦没．
