[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
chrono = "0.4.22"
once_cell = "1.13.1"
rand = "0.8.5"
ulid = "1.0.0"
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", tag = "v0.2.0" }
